// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uekjpewosraagvbbpjbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVla2pwZXdvc3JhYWd2YmJwamJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzkzMTksImV4cCI6MjA2NjcxNTMxOX0.EB-M4FjwVgT3SJQW-tcPSjhv0O-hqzvEbIvOOFpnbMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});